#name: Test
#on: [push]
#jobs:
#  test:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install Flutter
#        uses: subosito/flutter-action@v1
#      - name: Test app
#        run: flutter test --coverage
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: coverage/lcov.info
